# =============================== 核心配置 ================================
# ----------------- bot -------------------
bot:
  id: 123456
  pw: 654321

# ----------------- sizhi -----------------
sizhi:
  appId: "appid"

# --------------- spring ---------------
server:
  port: 8081

spring:
  profiles:
    active: dev

  # ================================= 连接配置 ==================================
  # ---------------- redis ----------------
  # ----------------- mysql ------------------
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:192.168.110.199:3306}/${DATABASE:ys_portal_dev}?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:slamacraft}
    password: ${DB_PASSWORD:13574159100Q}
    filters: stat,wall,log4j
  data:
    redis:
      password:
      database: 0
      host: localhost
      port: 6379
      timeout: 1000
